//
//  StyleKit.swift
//  SpinningShots
//
//  Created by Marc Zobec on 2015-10-11.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {

    //// Drawing Methods

    public class func drawCannon(frame frame: CGRect = CGRectMake(0, 0, 80, 100), cannonColor: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000), cannonStrokeColor: UIColor = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)) {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.83199 * frame.width, frame.minY + 0.20600 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.98750 * frame.width, frame.minY + 0.59800 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.92766 * frame.width, frame.minY + 0.32877 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.98750 * frame.width, frame.minY + 0.48464 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.50000 * frame.width, frame.minY + 0.99000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.98750 * frame.width, frame.minY + 0.81450 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.76924 * frame.width, frame.minY + 0.99000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.01250 * frame.width, frame.minY + 0.59800 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.23076 * frame.width, frame.minY + 0.99000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.01250 * frame.width, frame.minY + 0.81450 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.16801 * frame.width, frame.minY + 0.20600 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.01250 * frame.width, frame.minY + 0.48464 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.07234 * frame.width, frame.minY + 0.32877 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.13450 * frame.width, frame.minY + 0.20600 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.01250 * frame.width, frame.minY + 0.10800 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.06712 * frame.width, frame.minY + 0.20600 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.01250 * frame.width, frame.minY + 0.16201 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.13450 * frame.width, frame.minY + 0.01000 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.01250 * frame.width, frame.minY + 0.05388 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.06701 * frame.width, frame.minY + 0.01000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.86550 * frame.width, frame.minY + 0.01000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.98750 * frame.width, frame.minY + 0.10800 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.93288 * frame.width, frame.minY + 0.01000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.98750 * frame.width, frame.minY + 0.05399 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.86550 * frame.width, frame.minY + 0.20600 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.98750 * frame.width, frame.minY + 0.16212 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.93299 * frame.width, frame.minY + 0.20600 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.83199 * frame.width, frame.minY + 0.20600 * frame.height))
        bezierPath.closePath()
        bezierPath.usesEvenOddFillRule = true;

        cannonColor.setFill()
        bezierPath.fill()
        cannonStrokeColor.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()
    }

    public class func drawBullet(frame frame: CGRect = CGRectMake(0, 0, 25, 100), bulletColor: UIColor = UIColor(red: 0.500, green: 0.500, blue: 0.500, alpha: 1.000)) {

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPointMake(frame.minX + 0.91667 * frame.width, frame.minY + 0.84746 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.91667 * frame.width, frame.minY + 0.71187 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.71187 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.35488 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.66666 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint1: CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.29607 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.77709 * frame.width, frame.minY + 0.00000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.33332 * frame.width, frame.minY + 0.00000 * frame.height))
        bezierPath.addCurveToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.35488 * frame.height), controlPoint1: CGPointMake(frame.minX + 0.22288 * frame.width, frame.minY + 0.00000 * frame.height), controlPoint2: CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.29607 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.71187 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.08333 * frame.width, frame.minY + 0.71187 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.08333 * frame.width, frame.minY + 0.84746 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 0.84746 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.00000 * frame.width, frame.minY + 1.00000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 1.00000 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 1.00000 * frame.width, frame.minY + 0.84746 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.91667 * frame.width, frame.minY + 0.84746 * frame.height))
        bezierPath.addLineToPoint(CGPointMake(frame.minX + 0.91667 * frame.width, frame.minY + 0.84746 * frame.height))
        bezierPath.closePath()
        bezierPath.usesEvenOddFillRule = true;

        bulletColor.setFill()
        bezierPath.fill()
    }

}
