//
//  StyleKit.swift
//  SpinningShots
//
//  Created by Marc Zobec on 2015-10-06.
//  Copyright (c) 2015 . All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {

    //// Drawing Methods

    public class func drawCanvas1() {
    }

}
