# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
    "iPhone 5"
    #"iPhone 4s",
    #"iPhone 5",
    #"iPhone 6",
    #"iPhone 6 Plus"
    #"iPad Retina"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme "spinning shots"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

clear_previous_screenshots true

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help
